### ISSUE TITLE
请问您试过32位编译吗？在32位编译时会出现错误，感觉是internal/xencode.go中的部分参数为int而不是int64

### ISSUE THREAD

**Issue by jianfmax** [wangjq4214/buaa-login#1]
另：希望考虑去除internal。这样便于其他项目引用。望大神考虑一下。
另: 感觉编译的包有点大，是不是可以加上参数 ` -ldflags="-s -w" `，是不是可以让包小一点呢。

感谢大神的奉献！！！

**Comment by wangjq4214** [comment]
感谢你的建议，今天抽空修复一下

**Comment by wangjq4214** [comment]
你的建议都已经采纳，谢谢！
那我就把这个issue关掉了。
